// This file is auto-generated by tools/updateEnums.ts. DO NOT EDIT!

namespace mobs {
    export function isMonster(mob: number): boolean {
        switch (mob) {
            case MonsterMob.Zombie:
            case MonsterMob.Creeper:
            case MonsterMob.Skeleton:
            case MonsterMob.Spider:
            case MonsterMob.PigZombie:
            case MonsterMob.Slime:
            case MonsterMob.Enderman:
            case MonsterMob.Silverfish:
            case MonsterMob.CaveSpider:
            case MonsterMob.Ghast:
            case MonsterMob.LavaSlime:
            case MonsterMob.Blaze:
            case MonsterMob.ZombieVillager:
            case MonsterMob.Witch:
            case MonsterMob.Stray:
            case MonsterMob.Husk:
            case MonsterMob.WitherSkeleton:
            case MonsterMob.Guardian:
            case MonsterMob.ElderGuardian:
            case MonsterMob.Shulker:
            case MonsterMob.Endermite:
            case MonsterMob.Vindicator:
            case MonsterMob.Phantom:
            case MonsterMob.Ravager:
            case MonsterMob.Evoker:
            case MonsterMob.Vex:
            case MonsterMob.Drowned:
            case MonsterMob.Pillager:
            case MonsterMob.Hoglin:
            case MonsterMob.Piglin:
            case MonsterMob.Zoglin:
            case MonsterMob.Warden:
            case MonsterMob.Breeze:
            case MonsterMob.Creaking:
            case MonsterMob.EnderDragon:
            case MonsterMob.IronGolem:
            case MonsterMob.PiglinBrute:
            case MonsterMob.SnowGolem:
            case MonsterMob.Wither:
                return true;
        }
        return false;
    }
}